### ISSUE TITLE
A proper ReadME regarding what this does

### ISSUE THREAD

**Issue by DonaldTsang** [GrantGryczan/MSPFA#14]
Some questions that should be answered:
- What is this repo? What is MSPFA? (A webcomic host)
- What does this repo do? (Host MSPFA astories)
  - Can it be self hosted and if so, how to import? (Technical)
- What are the data used in MSPFA? (`x = JSON.stringify(MSPFA.story)`)
  - What does the keys mean? (lots of things)
  - What markup format does it use? (BBCode with embedded HTML)
    - How do I know which is which? (something related to the parser)
  - Are there any JS code within the data (yes but it should be used sparingly)

**Comment by GrantGryczan** [comment]
This repo is for the new site which I haven't really started working on yet. It's not for the current site, which is undocumented as it will soon be out of date.
